package eu.ismailozer.easyfilemanager;

import java.util.TreeSet;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JProgressBar;
import javax.swing.JRadioButton;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

public class MainGUIData_Save {
	/**
	 * Auto-generated main method to display this JFrame
	 */
	public JPanel pnlBottomCmdButton;
	public JPanel pnlInfo;
	public TreeSet<String> extTreeSet;
	public ButtonGroup btnGrpFileSize;
	public ButtonGroup btnGrpTransform;
	public JButton btnChooseCompareDir;
	public JButton btnChooseDir;
	public JButton btnClearAll;
	public JButton btnConvertImage;
	public JButton btnCopyFilesTo;
	public JButton btnCreateCSV;
	public JButton btnCreateXML;
	public JButton btnCreationFrom;
	public JButton btnCreationTo;
	public JButton btnDeleteDuplicateFilesLeft;
	public JButton btnDeleteDuplicateFilesRight;
	public JButton btnDeleteFiles;
	public JButton btnEditTextFile;
	public JButton btnExportTable;
	public JButton btnOpenFileFolder;
	public JButton btnOpenSelectedFile;
	public JButton btnOpenfile;
	public JButton btnRenameSelectedFiles;
	public JButton btnResetRenameOpt;
	public JButton btnResetSearchOpt;
	public JButton btnSearchFiles;
	public JButton btnSelectAll;
	public JButton btnRemoveFomList;
	public JButton btnViewLogFiles;
	public JButton btnZoomoutPicture;
	public JButton btnStopRunner;
	public JButton btnsearchDuplicateFiles;
	public JCheckBox cbxIncludeDirectories;
	public JCheckBox cbxIncludeFiles;
	public JCheckBox cbxLoggingCommandLine;
	public JCheckBox cbxLoggingInFile;
	public JCheckBox cbxRecursiveMode;
	public JCheckBox cbxResetCounter;
	public JComboBox<String> cbxBufferSize;
	public JComboBox<String> cbxBufferSizeFactor;
	public JComboBox<String> cbxFileExtentions;
	public JComboBox<String> cbxItemsLeft;
	public JComboBox<String> cbxItemsRight;
	public JComboBox<String> cbxLeadingZeros;
	public JComboBox<String> cbxLefOffset;
	public JComboBox<String> cbxRightOffset;
	public JComboBox<String> cbxSearchLimits;
	public JLabel lblBufferSize;
	public JLabel lblBufferSizeFactor;
	public JLabel lblCompareDir;
	public JLabel lblContainStr;
	public JLabel lblEndsWith;
	public JLabel lblFileInfo;
	public JLabel lblFileSize;
	public JLabel lblItemsLeft;
	public JLabel lblItemsRight;
	public JLabel lblLeftOffset;
	public JLabel lblPrefix;
	public JLabel lblRegExp;
	public JLabel lblRegexpReplaceNew;
	public JLabel lblRegexpReplaceOld;
	public JLabel lblReplWith;
	public JLabel lblReplace;
	public JLabel lblReplaceAll;
	public JLabel lblRightStart;
	public JLabel lblSequence;
	public JLabel lblSourceDir;
	public JLabel lblStartsWith;
	public JLabel lblSuffix;
	public JMenuItem menuItemCopyFilesTo;
	public JMenuItem menuItemEditTextFile;
	public JMenuItem menuItemOpenFileFolder;
	public JMenuItem openFileFolder;
	public JPanel pnlCompareDir;
	public JPanel pnlCompareFileOptions;
	public JPanel pnlDirectory;
	public JPanel pnlFilePreview;
	public JPanel pnlNoPreview;
	public JPanel pnlOptions;
	public JPanel pnlRenameOptions;
	public JPanel pnlSearchOptions;
	public JPanel pnlTableForCompare;
	public JPanel pnlTableForRenameFiles;
	public JPanel pnlTransformOpt;
	public JPopupMenu popupMenu;
	public JRadioButton rbtAllSize;
	public JRadioButton rbtCapitalize;
	public JRadioButton rbtFileSizeEqual;
	public JRadioButton rbtFileSizeGreater;
	public JRadioButton rbtFileSizeLower;
	public JRadioButton rbtLowerCase;
	public JRadioButton rbtNormal;
	public JRadioButton rbtParentAsFilename;
	public JRadioButton rbtUpperCase;
	public JScrollPane scrollPaneForCompare;
	public JScrollPane scrollPaneForRenameFiles;
	public JTabbedPane jTabbedPaneOptionsTop;
	public JTabbedPane jTabbedPanelForTables;
	public JTable tableCompareResult;
	public JTable tableSearchResult;
	public JTextField txtBufferSize;
	public JTextField txtBufferSizeFactor;
	public JTextField txtCompareDir;
	public JTextField txtContainStr;
	public JTextField txtEndsWith;
	public JTextField txtFileSize;
	public JTextField txtItemsLeft;
	public JTextField txtItemsRight;
	public JTextField txtLeftOffset;
	public JTextField txtPrefix;
	public JTextField txtRegexpReplaceNew;
	public JTextField txtRegexpReplaceOld;
	public JTextField txtReplaceAll;
	public JTextField txtReplaceNew;
	public JTextField txtReplaceOld;
	public JTextField txtRightOffset;
	public JTextField txtSearchDir;
	public JTextField txtSearchPattern;
	public JTextField txtSequence;
	public JTextField txtStartsWith;
	public JTextField txtSuffix;
	public JMenuBar menuBar;
	public JMenu menu;
	public JMenu submenu;
	public JMenuItem menuItem;
	public JMenuItem menuItemMoreLessItems;
	public JRadioButtonMenuItem rbMenuItem;
	public JCheckBoxMenuItem cbMenuItem;
	public JMenuItem menuItemImportToCompareTbl;
	public JProgressBar progressBar;
	public JCheckBox cbxSuccessiveUppercaseChars;

	public MainGUIData_Save(TreeSet<String> extTreeSet) {
		this.extTreeSet = extTreeSet;
	}
}